version: '3'
services:
  force-model:
    image: xdyn-force-grpc:python3
    command: harmonic_oscillator.py
    working_dir: /work
    volumes:
    - .:/work
    user: ${CURRENT_UID}
  xdyn:
    image: xdyn
    working_dir: /data
    entrypoint: ./wait-for-it.sh force-model:9002 -s -t 20 -- xdyn-for-cs tutorial_10_gRPC_force_model.yml --dt 0.1 -p 9002
    volumes:
    - .:/data
    user: ${CURRENT_UID}
    depends_on:
    - force-model
    environment:
    - no_proxy
  test:
    build: .
    user: ${CURRENT_UID}
    depends_on:
    - xdyn
    environment:
    - no_proxy
