version: '3'
services:
  waves-server:
    image: xdyn-waves-grpc:python3
    user: ${CURRENT_UID}
    command: airy.py
    working_dir: /work
    volumes:
    - .:/work
  xdyn:
    image: xdyn
    working_dir: /data
    entrypoint: ./wait-for-it.sh waves-server:50051 -s -t 20 -- xdyn-for-cs tutorial_09_gRPC_wave_model.yml --dt 0.1 -p 9002
    volumes:
    - .:/data
    user: ${CURRENT_UID}
    depends_on:
    - waves-server
    environment:
      - no_proxy
  test:
    build: .
    user: ${CURRENT_UID}
    depends_on:
    - xdyn
    environment:
      - no_proxy
